<?php

    function blog_roll_menu() {
        $items['path-to-ajax/%/%'] = array(
            'access arguments' => array('access content'),
            'page callback' => 'blog_roll_ajax_callback',
            'page arguments' => array(1,2),
            'type' => MENU_NORMAL_ITEM,
        );

        return $items;
    }

    function blog_roll_ajax_callback($js, $node_id) {
        $node = node_load($node_id);

        if($js == 'nojs') {
            drupal_goto('node/' . $node->nid);
        }

        $html = render(field_view_field('node', $node, 'body', array(
            'label' => 'hidden',
            'type' => 'text_summary_or_trimmed',
            'settings' => array('trim_length' => 100),
        )));

        $commands = array();
        $commands[] = ajax_command_html('#blog_roll-ajax-wrapper', $html);

        print ajax_render($commands);
        exit;
    }
